import { DashBord } from '@/features/dashboard-menu/dashboard-and-main/dashboard';
import { Header } from '@/features/dashboard-menu/header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Page Design Gallery',
  description: 'Generated by dash board menu',
};

export default function DashboardMenuLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <DashBord />
      <main>{children}</main>
    </div>
  );
}
