import { Footer } from '@/features/mega-menu-header/footer';
import { Header } from '@/features/mega-menu-header/header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Page Design Gallery',
  description: 'Generated by mega menu header',
};

export default function MegaMenuHeaderLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
