import { Footer } from '@/features/normal-header/footer';
import { Header } from '@/features/normal-header/header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Page Design Gallery',
  description: 'Generated by norlal header',
};

export default function NormalHeaderLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
